version: "3"

services:
  web_blue:
    container_name: web_blue
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command:
      - gunicorn
      - configs.wsgi:application
      - --config=/home/app/web/gunicorn.conf.py
    expose:
      - 8000
    entrypoint:
      - sh
      - configs/docker/entrypoint.prod.sh
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
      - ./logs/gunicorn-blue:/var/log/gunicorn
    env_file:
      - .env

  web_green:
    container_name: web_green
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command:
      - gunicorn
      - configs.wsgi:application
      - --config=/home/app/web/gunicorn.conf.py
    expose:
      - 8000
    entrypoint:
      - sh
      - configs/docker/entrypoint.prod.sh
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
      - ./logs/gunicorn-green:/var/log/gunicorn
    env_file:
      - .env

  nginx:
    container_name: nginx
    depends_on:
      - web_blue
    build: ./configs/nginx
    ports:
      - "80:80"
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
      - ./logs/nginx:/var/log/nginx
    environment:
      TZ: "Asia/Seoul"

volumes:
  static:
  media:
