# Generated by Django 5.2.9 on 2026-01-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('MAIN_GATE', '정문'), ('GRASS_GROUND', '잔디광장'), ('SPORT_TRACK', '스포츠트랙'), ('HYUUT_GIL', '휴웃길'), ('WELCH_RYANG_AUDITORIUM', '대강당'), ('EWHA_POSCO_BUILDING', '포스코관'), ('STUDENT_UNION', '학생문화관'), ('HUMAN_ECOLOGY_BUILDING', '생활환경관'), ('HAK_GWAN', '학관'), ('EDUCATION_BUILDING', '교육관'), ('EWHA_SHINSEGAE_BUILDING', '신세계관')], help_text='위치', max_length=50)),
                ('number', models.IntegerField(help_text='부스 번호/공연 시작 시각')),
            ],
        ),
    ]
