# Generated by Django 5.2.9 on 2026-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('GRASS_GROUND', '잔디광장'), ('SENTENNIAL_MUSEUM', '박물관'), ('SPORT_TRACK', '스포츠트랙'), ('HYUUT_GIL', '휴웃길'), ('WELCH_RYANG_AUDITORIUM', '대강당'), ('EWHA_POSCO_BUILDING', '포스코관'), ('STUDENT_UNION', '학생문화관'), ('HUMAN_ECOLOGY_BUILDING', '생활환경관'), ('HAK_GWAN', '학관'), ('EDUCATION_BUILDING', '교육관'), ('EWHA_SHINSEGAE_BUILDING', '신세계관')], help_text='위치', max_length=50),
        ),
    ]
