# Generated by Django 5.2.9 on 2026-04-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchs', '0002_alter_location_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['building', 'number']},
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.IntegerField(blank=True, help_text='부스 번호', null=True),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_building_number'),
        ),
    ]
