# Generated by Django 5.2.9 on 2026-02-01 08:02

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django_nanoid.models
import utils.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searchs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.CharField(help_text='예시:BOOTH_RELEASE', max_length=20, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, help_text='썸네일', null=True, upload_to=utils.helpers.FilePathBuilder('thumbnail'))),
                ('name', models.CharField(help_text='이름', max_length=20)),
                ('is_ongoing', models.BooleanField(help_text='운영중 여부')),
                ('description', models.CharField(blank=True, help_text='소개글', max_length=200, null=True)),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(), default=list, help_text='시간', size=None)),
                ('location_description', models.CharField(blank=True, help_text='위치 설명', max_length=50, null=True)),
                ('roadview', models.ImageField(blank=True, help_text='로드뷰 사진', null=True, upload_to=utils.helpers.FilePathBuilder('roadview'))),
                ('sns', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='SNS 링크', null=True, size=2)),
                ('admin_code', django_nanoid.models.NANOIDField(alphabetically='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', help_text='관리자 인증 코드', prefix=None, secure_generated=True, size=10)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FOOD', '음식'), ('GOODS', '굿즈'), ('EXPERIENCE', '체험')], max_length=10), default=list, help_text='카테고리', size=None)),
                ('host', models.CharField(choices=[('STUDENT', '학생'), ('COMMITTEE', '축준위'), ('SPONSOR', '협찬'), ('FLEA_MARKET', '플리마켓')], help_text='주관', max_length=20)),
                ('location', models.ForeignKey(help_text='위치', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='searchs.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoothNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=20)),
                ('content', models.CharField(help_text='내용', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='사진', null=True, upload_to=utils.helpers.FilePathBuilder('image'))),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('booth', models.ForeignKey(help_text='부스', on_delete=django.db.models.deletion.CASCADE, related_name='booth_notice', to='booths.booth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoothReviewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='익명 번호')),
                ('booth', models.ForeignKey(help_text='부스', on_delete=django.db.models.deletion.CASCADE, related_name='booth_review_user', to='booths.booth')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoothReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('user', models.ForeignKey(help_text='부스 후기 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='booth_review', to='booths.boothreviewuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoothScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('booth', models.ForeignKey(help_text='부스', on_delete=django.db.models.deletion.CASCADE, related_name='booth_scrap', to='booths.booth')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=20)),
                ('description', models.CharField(blank=True, help_text='설명', max_length=200, null=True)),
                ('price', models.IntegerField(help_text='가격')),
                ('image', models.ImageField(blank=True, help_text='사진', null=True, upload_to=utils.helpers.FilePathBuilder('image'))),
                ('is_selling', models.BooleanField(help_text='판매중 여부')),
                ('booth', models.ForeignKey(help_text='부스', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='booths.booth')),
            ],
        ),
    ]
