# Generated by Django 5.2.9 on 2026-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='host',
            field=models.CharField(choices=[('STUDENT', '학생'), ('COMMITTEE', '축준위'), ('SPONSOR', '협찬'), ('FLEA_MARKET', '플리마켓'), ('ETC', '기타')], help_text='주관', max_length=20),
        ),
    ]
