# Generated by Django 5.2.9 on 2026-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일시'),
        ),
    ]
