# Generated by Django 5.2.9 on 2026-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='admin_code',
        ),
        migrations.AddField(
            model_name='booth',
            name='admincode',
            field=models.CharField(default='ABCDE', editable=False, help_text='관리자 인증 코드', max_length=128),
            preserve_default=False,
        ),
    ]
