# Generated by Django 5.2.11 on 2026-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booths', '0001_initial'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_booth',
            field=models.ManyToManyField(help_text='부스 권한', related_name='user', to='booths.booth'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission_show',
            field=models.ManyToManyField(help_text='공연 권한', related_name='user', to='shows.show'),
        ),
    ]
