# Generated by Django 5.2.9 on 2026-01-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booths', '0001_initial'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_booth',
            field=models.ManyToManyField(blank=True, help_text='부스 권한', related_name='user', to='booths.booth'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission_show',
            field=models.ManyToManyField(blank=True, help_text='공연 권한', related_name='user', to='shows.show'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
