# Generated by Django 5.2.9 on 2026-01-31 16:19

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django_nanoid.models
import utils.abstracts
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searchs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.CharField(help_text='예시:BOOTH_RELEASE', max_length=20, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, help_text='썸네일', null=True, upload_to=utils.abstracts.get_thumbnail_path)),
                ('name', models.CharField(help_text='이름', max_length=20)),
                ('is_ongoing', models.BooleanField(help_text='운영중 여부')),
                ('description', models.CharField(blank=True, help_text='소개글', max_length=200, null=True)),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(), default=list, help_text='시간', size=None)),
                ('location_description', models.CharField(blank=True, help_text='위치 설명', max_length=50, null=True)),
                ('roadview', models.ImageField(blank=True, help_text='로드뷰 사진', null=True, upload_to=utils.abstracts.get_roadview_path)),
                ('sns', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='SNS 링크', null=True, size=2)),
                ('admin_code', django_nanoid.models.NANOIDField(alphabetically='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', help_text='관리자 인증 코드', prefix=None, secure_generated=True, size=10)),
                ('category', models.CharField(choices=[('BAND', '밴드'), ('DANCE', '댄스'), ('THEATER', '연극')], help_text='카테고리', max_length=10)),
                ('location', models.ForeignKey(help_text='위치', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='searchs.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=20)),
                ('show', models.ForeignKey(help_text='공연', on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='shows.show')),
            ],
        ),
        migrations.CreateModel(
            name='ShowNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=20)),
                ('content', models.CharField(help_text='내용', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='사진', null=True, upload_to=utils.abstracts.get_notice_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('show', models.ForeignKey(help_text='공연', on_delete=django.db.models.deletion.CASCADE, related_name='show_notice', to='shows.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowReviewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='익명 번호')),
                ('show', models.ForeignKey(help_text='공연', on_delete=django.db.models.deletion.CASCADE, related_name='show_review_user', to='shows.show')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('user', models.ForeignKey(help_text='공연 후기 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='show_review', to='shows.showreviewuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('show', models.ForeignKey(help_text='공연', on_delete=django.db.models.deletion.CASCADE, related_name='show_scrap', to='shows.show')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
