# Generated by Django 5.2.9 on 2026-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='admin_code',
        ),
        migrations.AddField(
            model_name='show',
            name='admincode',
            field=models.CharField(default='ABCDE', editable=False, help_text='관리자 인증 코드', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.CharField(choices=[('BAND', '밴드'), ('VOCAL', '보컬'), ('DANCE', '댄스'), ('THEATER', '연극'), ('ARTIST', '아티스트')], help_text='카테고리', max_length=10),
        ),
    ]
