# Generated by Django 5.2.9 on 2026-02-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shownotice',
            name='created_at',
        ),
        migrations.AddField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일시'),
        ),
    ]
