# Generated by Django 5.2.9 on 2026-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shownotice',
            name='image',
        ),
        migrations.AlterField(
            model_name='shownotice',
            name='title',
            field=models.CharField(help_text='제목', max_length=40),
        ),
    ]
