# Generated by Django 5.2.9 on 2026-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_remove_shownotice_created_at_show_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='생성일시'),
        ),
    ]
