# Generated by Django 5.2.9 on 2026-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_remove_shownotice_image_alter_shownotice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='name',
            field=models.CharField(help_text='이름', max_length=40),
        ),
    ]
