# Generated by Django 5.2.9 on 2026-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_shownotice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shownotice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일시'),
        ),
    ]
