# Generated by Django 5.2.9 on 2026-02-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_alter_shownotice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='created_at',
        ),
    ]
